python ct_vocabfine_train.py \
    --lr 1e-5 \
    --wd 0.1 \
    --epochs 10 \
    --feature_size 96 \
    --warmup_length 10000 \
    --save ./exps_large/ \
    --swin_pretrained /pretrained/VoCo_H_SSL_head.pt \
    --pretrained /checkpoints/CT-CLIP/CT_CLIP_zeroshot.pt \
    --data-folder /CT-RATE/train_preprocessed/ \
    --reports-file /CT-RATE/dataset/radiology_text_reports/train_reports.csv \
    --labels /CT-RATE/dataset/multi_abnormality_labels/train_predicted_labels.csv